name: The Otomoto
favicon: null
layout_spectrum: 0.7284803343936801
typography_spectrum: 0.5709557258524001
title: Otomoto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f1f1'
    - '#333333'
    - '#838181'
    - '#535353'
    - '#d4d2d2'
  brandStrength: 0.48965804814361036
  lightness: 0.6875
  saturation: 0.060913828667253256
  rhythmicContrast: 0.43584556807763875
purpose: []
